print("문자 선택 연산자")
print("Python[-1] : " + "Python"[-1])
print("Python[-2] : " + "Python"[-2])
print("Python[-3] : " + "Python"[-3])
print("Python[-4] : " + "Python"[-4])
print("Python[-5] : " + "Python"[-5])
print("Python[-6] : " + "Python"[-6])
